apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app.kubernetes.io/name: nginx
  ports:
    - name: nginx
      protocol: TCP
      port: 80
      targetPort: 9376
  externalIPs:
    - 172.31.137.87
