kind: Service
apiVersion: v1
metadata:
  labels:
    name: apache-lb
  name: apache-lb
  namespace: basic
spec:
  ports:
    - port: 8080
      targetPort: 8088
  externalIPs:
    - 172.31.137.87
  selector:
    app: apache
  type: LoadBalancer
